DROP ALL OBJECTS;

CREATE TABLE IF NOT EXISTS users
(
    id    BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    name  VARCHAR                                 NOT NULL,
    email VARCHAR UNIQUE                          NOT NULL,
    CONSTRAINT user_id_pk PRIMARY KEY (id)
);

CREATE UNIQUE INDEX IF NOT EXISTS users_email_uindex
    ON users (email);

CREATE UNIQUE INDEX IF NOT EXISTS users_id_uindex
    ON users (id);

CREATE TABLE IF NOT EXISTS items
(
    id           BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    name         VARCHAR                                 NOT NULL,
    description  VARCHAR                                 NOT NULL,
    is_available BOOLEAN                                 NOT NULL,
    owner_id     BIGINT                                  NOT NULL,
    CONSTRAINT item_id_pk PRIMARY KEY (id),
    CONSTRAINT items_user_id_fk FOREIGN KEY (owner_id) REFERENCES users
);

CREATE UNIQUE INDEX IF NOT EXISTS items_id_uindex
    ON items (id);

CREATE TABLE IF NOT EXISTS bookings
(
    id         BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    start_date TIMESTAMP WITHOUT TIME ZONE             NOT NULL,
    end_date   TIMESTAMP WITHOUT TIME ZONE             NOT NULL,
    item_id    BIGINT REFERENCES items (id)            NOT NULL,
    booker_id  BIGINT REFERENCES users (id)            NOT NULL,
    status     VARCHAR                                 NOT NULL,
    CONSTRAINT bookings_id_pk PRIMARY KEY (id)
);

CREATE UNIQUE INDEX IF NOT EXISTS bookings_id_uindex
    ON bookings (id);

CREATE TABLE IF NOT EXISTS comments
(
    comment_id BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    text       VARCHAR                                 NOT NULL,
    item_id    BIGINT REFERENCES items (id)            NOT NULL,
    author_id  BIGINT REFERENCES users (id)            NOT NULL,
    created    TIMESTAMP WITHOUT TIME ZONE             NOT NULL,
    PRIMARY KEY (comment_id)
);

CREATE TABLE IF NOT EXISTS requests
(
    request_id   BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    description  VARCHAR NOT NULL,
    requestor_id BIGINT REFERENCES users (id) ON DELETE CASCADE,
    created      TIMESTAMP WITHOUT TIME ZONE DEFAULT CURRENT_TIMESTAMP
);

ALTER TABLE items
    ADD COLUMN target_request_id BIGINT REFERENCES requests (request_id) ON DELETE CASCADE;